apiVersion: v1
kind: Pod
metadata:
  name: workload
  namespace: sandbox
spec:
  containers:
    - name: client-workload
      # image: alpine/openssl
      image: quay.io/ckyal/aws-rolesanywhere:latest
      command: ["sh", "-c", "sleep 3600"]
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
        requests:
          memory: "64Mi"
          cpu: "250m"

      volumeMounts:
        - mountPath: "/var/run/secrets/certificate"
          name: certificate

  volumes:
    - name: certificate
      csi:
        driver: csi.cert-manager.io
        readOnly: true
        volumeAttributes:
          csi.cert-manager.io/issuer-name: vault-issuer
          csi.cert-manager.io/issuer-kind: Issuer
          csi.cert-manager.io/issuer-group: cert-manager.io

          csi.cert-manager.io/dns-names: test.example.com
          csi.cert-manager.io/uri-sans: "spiffe://example.com/ns/${POD_NAMESPACE}/pod/${POD_NAME}"
